packages:
  - 'packages/*'

allowBuilds:
  electron: true
  esbuild: true
  ssh2: false
  cpu-features: false
  protobufjs: false
  electron-winstaller: false
  kerberos: false
  mongodb-client-encryption: false
  os-dns-native: false
