import type { ProfileEntry } from '@mongo-gui/core';

const BASE_MS = Date.parse('2026-10-10T09:00:00.000Z');
const STEP_MS = 41_000;

/** A timestamp for the entry at this position. Each entry gets its own second, so rows stay apart. */
function stamp(position: number): string {
  return new Date(BASE_MS + position * STEP_MS).toISOString();
}

/** A filter nested this many levels deep, with a long $in list, for the huge-command scenario. */
function hugeFilter(depth: number): unknown {
  let node: unknown = { status: { $in: Array.from({ length: 500 }, (_, index) => `s-${index}`) } };
  for (let level = depth; level > 0; level -= 1) {
    node = { $or: [{ $and: [node, { level }] }, { depth: { $gte: level } }] };
  }
  return node;
}

/** One profiler row per kind of operation, plan and counter the ProfileEntry schema can hold. */
export const profilerScenarios: readonly ProfileEntry[] = [
  {
    id: 'sc-01-collscan',
    ts: stamp(0),
    ns: 'shop.orders',
    op: 'query',
    millis: 180,
    command: { find: 'orders', filter: { status: 'paid' }, limit: 10 },
    planSummary: 'COLLSCAN',
    docsExamined: 5000,
    keysExamined: 0,
    nreturned: 10,
    client: '10.0.0.12',
    appName: 'checkout-api',
    raw: {},
  },
  {
    id: 'sc-02-ixscan',
    ts: stamp(1),
    ns: 'shop.orders',
    op: 'query',
    millis: 4,
    command: { find: 'orders', filter: { status: 'pending' } },
    planSummary: 'IXSCAN { status: 1 }',
    docsExamined: 40,
    keysExamined: 40,
    nreturned: 40,
    raw: {},
  },
  {
    id: 'sc-03-sort',
    ts: stamp(2),
    ns: 'shop.orders',
    op: 'query',
    millis: 25,
    command: { find: 'orders', filter: { status: 'pending' }, sort: { createdAt: -1 } },
    planSummary: 'IXSCAN { status: 1, createdAt: -1 }',
    hasSortStage: true,
    usedDisk: false,
    docsExamined: 40,
    keysExamined: 40,
    nreturned: 40,
    raw: {},
  },
  {
    id: 'sc-04-ratio',
    ts: stamp(3),
    ns: 'shop.orders',
    op: 'query',
    millis: 60,
    command: { find: 'orders', filter: { customerId: 'c-17' } },
    planSummary: 'IXSCAN { customerId: 1 }',
    docsExamined: 5000,
    keysExamined: 5000,
    nreturned: 20,
    raw: {},
  },
  {
    id: 'sc-05-empty',
    ts: stamp(4),
    ns: 'shop.orders',
    op: 'query',
    millis: 41,
    command: { find: 'orders', filter: { status: 'refunded', total: { $gt: 99999 } } },
    planSummary: 'IXSCAN { status: 1 }',
    docsExamined: 3000,
    keysExamined: 3000,
    nreturned: 0,
    raw: {},
  },
  {
    id: 'sc-06-update',
    ts: stamp(5),
    ns: 'shop.customers',
    op: 'update',
    millis: 3,
    command: {
      q: { email: 'ada@example.com' },
      u: { $set: { lastSeen: '2026-10-10' } },
      multi: false,
      upsert: false,
    },
    planSummary: 'IXSCAN { email: 1 }',
    docsExamined: 1,
    keysExamined: 1,
    nMatched: 1,
    nModified: 1,
    locks: { Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { w: 1 } } },
    client: '10.0.0.40',
    appName: 'fulfilment-worker',
    raw: {},
  },
  {
    id: 'sc-07-remove',
    ts: stamp(6),
    ns: 'shop.orders',
    op: 'remove',
    millis: 33,
    command: { q: { status: 'cancelled' }, limit: 0 },
    planSummary: 'COLLSCAN',
    docsExamined: 800,
    keysExamined: 0,
    raw: {},
  },
  {
    id: 'sc-08-insert',
    ts: stamp(7),
    ns: 'shop.events',
    op: 'insert',
    millis: 2,
    command: { insert: 'events', ordered: true, documents: [{ kind: 'click', at: 1 }] },
    client: '10.0.0.50',
    raw: {},
  },
  {
    id: 'sc-09-getmore',
    ts: stamp(8),
    ns: 'shop.orders',
    op: 'getmore',
    millis: 12,
    command: {
      getMore: 4417,
      collection: 'orders',
      batchSize: 101,
      originatingCommand: { find: 'orders', filter: { status: 'paid' }, batchSize: 101 },
    },
    docsExamined: 100,
    nreturned: 100,
    raw: {},
  },
  {
    id: 'sc-10-getmore-orphan',
    ts: stamp(9),
    ns: 'shop.customers',
    op: 'getmore',
    millis: 1,
    command: { getMore: 9001, collection: 'customers' },
    nreturned: 50,
    raw: {},
  },
  {
    id: 'sc-11-aggregate',
    ts: stamp(10),
    ns: 'shop.orders',
    op: 'command',
    millis: 88,
    command: {
      aggregate: 'orders',
      pipeline: [
        { $match: { status: 'paid' } },
        { $group: { _id: '$customerId', total: { $sum: '$totalCents' } } },
        { $sort: { total: -1 } },
        { $limit: 10 },
      ],
      cursor: {},
    },
    planSummary: 'IXSCAN { status: 1 }',
    docsExamined: 300,
    keysExamined: 300,
    nreturned: 10,
    raw: {},
  },
  {
    id: 'sc-12-lookup',
    ts: stamp(11),
    ns: 'shop.orders',
    op: 'command',
    millis: 2100,
    command: {
      aggregate: 'orders',
      pipeline: [
        {
          $lookup: {
            from: 'customers',
            localField: 'customerId',
            foreignField: '_id',
            as: 'customer',
          },
        },
        { $unwind: '$customer' },
      ],
      cursor: {},
    },
    planSummary: 'COLLSCAN',
    docsExamined: 48000,
    keysExamined: 0,
    nreturned: 300,
    raw: {},
  },
  {
    id: 'sc-13-count',
    ts: stamp(12),
    ns: 'shop.orders',
    op: 'command',
    millis: 14,
    command: { count: 'orders', query: { status: 'paid' } },
    planSummary: 'COUNT_SCAN { status: 1 }',
    keysExamined: 4000,
    nreturned: 1,
    raw: {},
  },
  {
    id: 'sc-14-distinct',
    ts: stamp(13),
    ns: 'shop.customers',
    op: 'command',
    millis: 210,
    command: { distinct: 'customers', key: 'email', query: {} },
    planSummary: 'COLLSCAN',
    docsExamined: 9100,
    keysExamined: 0,
    nreturned: 9100,
    raw: {},
  },
  {
    id: 'sc-15-findandmodify',
    ts: stamp(14),
    ns: 'shop.orders',
    op: 'command',
    millis: 2,
    command: {
      findAndModify: 'orders',
      query: { _id: 'o-1001' },
      update: { $set: { status: 'shipped' } },
      new: true,
    },
    planSummary: 'IDHACK',
    docsExamined: 1,
    keysExamined: 1,
    nMatched: 1,
    nModified: 1,
    nreturned: 1,
    raw: {},
  },
  {
    id: 'sc-16-no-plan',
    ts: stamp(15),
    ns: 'shop.orders',
    op: 'query',
    millis: 5,
    command: { find: 'orders', filter: {} },
    docsExamined: 10,
    nreturned: 10,
    raw: {},
  },
  {
    id: 'sc-17-error',
    ts: stamp(16),
    ns: 'shop.orders',
    op: 'command',
    millis: 40,
    command: { find: 'orders', filter: {}, sort: { totalCents: -1 } },
    planSummary: 'COLLSCAN',
    hasSortStage: true,
    usedDisk: false,
    docsExamined: 2000,
    keysExamined: 0,
    errMsg: 'Sort exceeded memory limit of 33554432 bytes, but did not opt in to external sorting.',
    errCode: 96,
    raw: {},
  },
  {
    id: 'sc-18-long',
    ts: stamp(17),
    ns: 'shop.orders',
    op: 'command',
    millis: 12_500,
    command: {
      aggregate: 'orders',
      pipeline: [{ $match: {} }, { $group: { _id: '$status', n: { $sum: 1 } } }],
      cursor: {},
    },
    planSummary: 'COLLSCAN',
    docsExamined: 48000,
    keysExamined: 0,
    nreturned: 4,
    raw: {},
  },
  {
    id: 'sc-19-zero',
    ts: stamp(18),
    ns: 'shop.customers',
    op: 'query',
    millis: 0,
    command: { find: 'customers', filter: { _id: 'c-0' } },
    planSummary: 'IDHACK',
    docsExamined: 0,
    keysExamined: 0,
    nreturned: 0,
    raw: {},
  },
  {
    id: 'sc-20-huge',
    ts: stamp(19),
    ns: 'shop.orders',
    op: 'command',
    millis: 19,
    command: { find: 'orders', filter: hugeFilter(40), limit: 3 },
    planSummary: 'IXSCAN { status: 1 }',
    docsExamined: 12,
    keysExamined: 12,
    nreturned: 3,
    raw: {},
  },
  {
    id: 'sc-21-keys-only',
    ts: stamp(20),
    ns: 'shop.orders',
    op: 'query',
    millis: 3,
    command: { find: 'orders', filter: { customerId: 'c-9' } },
    planSummary: 'IXSCAN { customerId: 1 }',
    keysExamined: 12,
    nreturned: 5,
    raw: {},
  },
  {
    id: 'sc-22-system',
    ts: stamp(21),
    ns: 'shop.system.js',
    op: 'query',
    millis: 1,
    command: { find: 'system.js', filter: {} },
    planSummary: 'COLLSCAN',
    docsExamined: 3,
    nreturned: 3,
    raw: {},
  },
  {
    id: 'sc-23-far-past',
    ts: '1999-03-01T12:00:00.000Z',
    ns: 'shop.orders',
    op: 'query',
    millis: 6,
    command: { find: 'orders', filter: { status: 'paid' } },
    planSummary: 'IXSCAN { status: 1 }',
    docsExamined: 3,
    keysExamined: 3,
    nreturned: 3,
    raw: {},
  },
];
