// Built-in role names and privilege actions, taken from the MongoDB manual. Grouped by the
// categories the manual uses so the UI can render pickers without a second copy of the list.

export const BUILTIN_ROLES = {
  databaseUser: ['read', 'readWrite'],
  databaseAdmin: ['dbAdmin', 'dbOwner', 'userAdmin'],
  clusterAdmin: ['clusterAdmin', 'clusterManager', 'clusterMonitor', 'hostManager'],
  backupRestore: ['backup', 'restore'],
  allDatabase: [
    'readAnyDatabase',
    'readWriteAnyDatabase',
    'userAdminAnyDatabase',
    'dbAdminAnyDatabase',
  ],
  superuser: ['root'],
  internal: ['__system'],
} as const;

export const PRIVILEGE_ACTIONS = {
  queryAndWrite: ['find', 'insert', 'remove', 'update', 'bypassDocumentValidation', 'useUUID'],
  databaseManagement: [
    'changeCustomData',
    'changeOwnCustomData',
    'changeOwnPassword',
    'changePassword',
    'createCollection',
    'createIndex',
    'createRole',
    'createUser',
    'dropCollection',
    'dropRole',
    'dropUser',
    'enableProfiler',
    'grantRole',
    'killCursors',
    'killAnyCursor',
    'planCacheIndexFilter',
    'querySettings',
    'revokeRole',
    'setAuthenticationRestriction',
    'setFeatureCompatibilityVersion',
    'unlock',
    'viewRole',
    'viewUser',
  ],
  deploymentManagement: [
    'authSchemaUpgrade',
    'cleanupOrphaned',
    'cpuProfiler',
    'inprog',
    'invalidateUserCache',
    'killop',
    'planCacheRead',
    'planCacheWrite',
  ],
  changeStream: ['changeStream'],
  replication: [
    'appendOplogNote',
    'replSetConfigure',
    'replSetGetConfig',
    'replSetGetStatus',
    'replSetHeartbeat',
    'replSetStateChange',
    'resync',
  ],
  sharding: [
    'addShard',
    'analyzeShardKey',
    'checkMetadataConsistency',
    'clearJumboFlag',
    'enableSharding',
    'refineCollectionShardKey',
    'moveCollection',
    'reshardCollection',
    'rewriteCollection',
    'unshardCollection',
    'flushRouterConfig',
    'getClusterParameter',
    'getShardMap',
    'listShards',
    'moveChunk',
    'removeShard',
    'shardedDataDistribution',
    'shardingState',
    'splitChunk',
    'transitionFromDedicatedConfigServer',
    'transitionToDedicatedConfigServer',
  ],
  serverAdministration: [
    'applicationMessage',
    'bypassWriteBlockingMode',
    'bypassDefaultMaxTimeMS',
    'closeAllDatabases',
    'collMod',
    'compact',
    'compactStructuredEncryptionData',
    'connPoolSync',
    'convertToCapped',
    'dropConnections',
    'dropDatabase',
    'dropIndex',
    'forceUUID',
    'fsync',
    'getDefaultRWConcern',
    'getParameter',
    'hostInfo',
    'oidReset',
    'logRotate',
    'reIndex',
    'renameCollectionSameDB',
    'rotateCertificates',
    'setDefaultRWConcern',
    'setParameter',
    'setUserWriteBlockMode',
    'shutdown',
    'touch',
  ],
  session: ['impersonate', 'listSessions', 'killAnySession'],
  searchIndex: ['createSearchIndexes', 'dropSearchIndex', 'listSearchIndexes', 'updateSearchIndex'],
  // The current manual has no free monitoring section. These two actions gate the free
  // monitoring commands of servers from 4.4 and earlier.
  freeMonitoring: ['checkFreeMonitoringStatus', 'setFreeMonitoring'],
  diagnostic: [
    'collStats',
    'connPoolStats',
    'dbHash',
    'dbStats',
    'getCmdLineOpts',
    'getLog',
    'indexStats',
    'listClusterCatalog',
    'listDatabases',
    'listCollections',
    'listIndexes',
    'queryStatsRead',
    'queryStatsReadTransformed',
    'serverStatus',
    'validate',
    'top',
  ],
  internal: ['anyAction', 'internal', 'applyOps'],
} as const;

const BUILTIN_ROLE_NAMES: ReadonlySet<string> = new Set(
  Object.values(BUILTIN_ROLES).flatMap((names) => names),
);

export function isBuiltinRole(role: string): boolean {
  return BUILTIN_ROLE_NAMES.has(role);
}
